Tittel: Beethoven - Egmont ouverture
Komponist: Ludwig van Beethoven
Orgtittel: Ouverture zu Goethes Trauerspiel Egmont
Arr: 
Skap:
Skuff: 1
Mappe: 24
Solist: Nei
Partitur: Ja
Mangler: Nei
Kommentar: 